on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
          rversion: 4.0
        - os: ubuntu-latest
          rversion: 4.0
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        if: runner.os == 'macOS'
        with:
          r-version: ${{ matrix.rversion }}
      
      - name: check where R is installed
        if: runner.os == 'macOS'
        run: |
          which R
          Rscript -e 'print(.libPaths())'
      
      - name: get xml2
        if: runner.os == 'macOS'
        run: |
          brew install libxml2
          touch ~/.zshrc
          echo 'export PATH="/usr/local/opt/libxml2/bin:$PATH"' >> ~/.zshrc
      
      - name: set up workflow R for macOS
        if: runner.os == 'macOS'
        run: |
          sed -i .bak 's/useCondaR: True/useCondaR: False/' config.yaml
          mkdir -p $HOME/Rlib
          echo "R_LIBS_USER=${HOME}/Rlib" > .Renviron
          cat .Renviron
          Rscript -e "install.packages('BiocManager'); BiocManager::install('GenomeInfoDbData')"
          
      - name: setup conda
        uses: s-weigand/setup-conda@v1.0.2
        with:
          activate-conda: true
          update-conda: true
          conda-channels: 'bioconda,conda-forge,defaults'
      
      - name: install snakemake and run workflow
        run: |
          conda install snakemake=5.16.0
          mkdir -p $HOME/.R
          echo -e 'MAKEFLAGS = -j8' > $HOME/.R/Makevars
          echo 'options(Ncpus = 8)' > $HOME/.Rprofile
          snakemake --use-conda --cores 4
      
      - name: upload artifact
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: install_pkgs_rout
          path: example_data/output/Rout/install_pkgs.Rout
