on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ubuntu-latest
    steps:
      - uses: snakemake/snakemake-github-action@v1.4.2
        with:
          directory: '.test'
          snakefile: 'Snakefile'
          args: '--use-conda'
          stagein: '' # additional preliminary commands to run (can be multiline)
