on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
        - os: macos-latest
          rversion: 3.6
        - os: ubuntu-latest
          rversion: 3.6
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@master
        if: runner.os == 'macOS'
        with:
          r-version: ${{ matrix.r }}
      
      - name: check where R is installed
        if: runner.os == 'macOS'
        run: |
          echo which R
          Rscript -e 'print(.libPaths())'
      
