on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install snakemake and run workflow
        run: |
          source /usr/share/miniconda/etc/profile.d/conda.sh
          conda activate base
          conda install --yes -c bioconda -c conda-forge snakemake=5.8.1
          snakemake --use-conda checkinputs
