on:
  push:
  pull_request:
    branches:
      - master

name: snakemake-run

jobs:
  snakemake-run:
    name: run snakemake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: macos-latest
          condafile: $HOME/miniconda/etc/profile.d/conda.sh
        - os: ubuntu-latest
          condafile: /usr/share/miniconda/etc/profile.d/conda.sh
    steps:
      - uses: actions/checkout@v2
      - name: install snakemake and run workflow
        run: |
          source ${{ matrix.condafile }}
          conda activate base
          conda update -n base -c defaults conda
          conda install --yes -c bioconda -c conda-forge snakemake=5.8.1
          mkdir -p ~/.R
          echo -e 'MAKEFLAGS = -j8' > ~/.R/Makevars
          echo 'options(Ncpus = 8)' > ~/.Rprofile
          snakemake --use-conda

